import "../styles/style.css"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsApp from "@/components/WhatsApp"


export const metadata = {
  title: "Neria's dresses",
  description: "Generated by Ido Sabach",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen ">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
        <WhatsApp />
      </body>
    </html>
  );
}
